[package]
name = "mindmodel_launcher"
version = "0.1.1"
edition = "2021"
description = "MindModel Launcher - 释放并启动 MindModel 应用"

[build-dependencies]
winres = "0.1"

[dependencies]
include_dir = { version = "0.7", features = ["glob"] }
zip = "2"
